repos:
- repo: https://github.com/standard/standard
  rev: v16.0.3
  hooks:
    - id: standard
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v5.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['cz-conventional-changelog']